function(print_target_libraries target msg)
    get_target_property(link_libs               ${target} LINK_LIBRARIES)
    get_target_property(link_libs_interface     ${target} INTERFACE_LINK_LIBRARIES)
    get_target_property(include_libs            ${target} INCLUDE_DIRECTORIES)
    get_target_property(include_libs_interface  ${target} INTERFACE_INCLUDE_DIRECTORIES)
    get_target_property(link_dirs               ${target} LINK_DIRECTORIES)
    get_target_property(link_dirs_interface     ${target} INTERFACE_LINK_DIRECTORIES)

    message("====================================")
    message("${target} 속성 정보")
    list(LENGTH link_libs link_libs_count)
    if (${link_libs_count} GREATER 0)
        message("LINK_LIBRARIES:")
        message("${link_libs}")
    endif()

    list(LENGTH link_libs_interface link_libs_interface_count)
    if (${link_libs_interface_count} GREATER 0)
        message("INTERFACE_LINK_LIBRARIES:")
        message("${link_libs_interface}")
    endif()
    
    message("INTERFACE_LINK_LIBRARIES:")
    message("${link_libs_interface}")
    message("INCLUDE_DIRECTORIES:")
    message("${include_libs}")
    message("INTERFACE_INCLUDE_DIRECTORIES:")
    message("${include_libs_interface}")
    message("LINK_DIRECTORIES:")
    message("${link_dirs}")
    message("INTERFACE_LINK_DIRECTORIES:")
    message("${link_dirs_interface}")
    message("====================================")
endfunction()


